### ISSUE TITLE
working issue

### ISSUE THREAD

**Issue by shrutik27** [googlecodelabs/google-maps-nearby-search-js#6]
i am geeting an issue in which it state
This page didn't load Google Maps correctly. See the JavaScript console for technical details.
i have placed api key and not changed ay other thing. help me in solving it

**Comment by shrutik27** [comment]
as per new google cloud service we need to set up paying account and i solved this issue without changing my code

**Comment by kartikeyahl** [comment]
> as per new google cloud service we need to set up paying account and i solved this issue without changing my code

how to create one?? and did you kept the API key same as in repo??
